### ISSUE TITLE
Linux binaries

### ISSUE THREAD

**Issue by warlord0** [techno-express/node-7z#1]
Firstly, thanks for a great bit of code. Really liking it for the cross platform capabilities.

I ran into a problem that not directly related to the project code, stopped me from installing it under Linux. On Windows no problem, but Linux failed to deliver the necessary binaries.

I then ran `yarn` with the `--verbose` switch and could see the install required to run `sudo` and failed because there was no tty for me to put in a password.

```console
Downloading http://cfhcable.dl.sourceforge.net/project/p7zip/p7zip/16.02/p7zip_16.02_x86_linux_bin.tar.bz2
info command unar SOURCEFILE -o /home/myuser/cybre/node_modules/node-7z-forall/linux -f -D
info cmd unar "/home/myuser/cybre/node_modules/node-7z-forall/p7zip_16.02_x86_linux_bin.tar.bz2" -o /home/myuser/cybre/node_modules/node-7z-forall/linux -f -D
Running sudo apt-get,install,libc6-i386,-y
Downloading http://cfhcable.dl.sourceforge.net/project/p7zip/p7zip/16.02/p7zip_16.02_x86_linux_bin.tar.bz2
info command unar SOURCEFILE -o /home/myuser/cybre/node_modules/node-7z-forall/linux -f -D
info cmd unar "/home/myuser/cybre/node_modules/node-7z-forall/p7zip_16.02_x86_linux_bin.tar.bz2" -o /home/myuser/cybre/node_modules/node-7z-forall/linux -f -D
Running sudo apt-get,install,libc6-i386,-y
Downloading http://cfhcable.dl.sourceforge.net/project/p7zip/p7zip/16.02/p7zip_16.02_x86_linux_bin.tar.bz2
info command unar SOURCEFILE -o /home/myuser/cybre/node_modules/node-7z-forall/linux -f -D
info cmd unar "/home/myuser/cybre/node_modules/node-7z-forall/p7zip_16.02_x86_linux_bin.tar.bz2" -o /home/myuser/cybre/node_modules/node-7z-forall/linux -f -D
Running sudo apt-get,install,libc6-i386,-y
Downloading http://cfhcable.dl.sourceforge.net/project/p7zip/p7zip/16.02/p7zip_16.02_x86_linux_bin.tar.bz2
info command unar SOURCEFILE -o /home/myuser/cybre/node_modules/node-7z-forall/linux -f -D
info cmd unar "/home/myuser/cybre/node_modules/node-7z-forall/p7zip_16.02_x86_linux_bin.tar.bz2" -o /home/myuser/cybre/node_modules/node-7z-forall/linux -f -D
Running sudo apt-get,install,libc6-i386,-y
Downloading http://cfhcable.dl.sourceforge.net/project/p7zip/p7zip/16.02/p7zip_16.02_x86_linux_bin.tar.bz2
info command unar SOURCEFILE -o /home/myuser/cybre/node_modules/node-7z-forall/linux -f -D
info cmd unar "/home/myuser/cybre/node_modules/node-7z-forall/p7zip_16.02_x86_linux_bin.tar.bz2" -o /home/myuser/cybre/node_modules/node-7z-forall/linux -f -D
Running sudo apt-get,install,libc6-i386,-y
Downloading http://cfhcable.dl.sourceforge.net/project/p7zip/p7zip/16.02/p7zip_16.02_x86_linux_bin.tar.bz2
info command unar SOURCEFILE -o /home/myuser/cybre/node_modules/node-7z-forall/linux -f -D
info cmd unar "/home/myuser/cybre/node_modules/node-7z-forall/p7zip_16.02_x86_linux_bin.tar.bz2" -o /home/myuser/cybre/node_modules/node-7z-forall/linux -f -D
Running sudo apt-get,install,libc6-i386,-y
Error: sudo: no tty present and no askpass program specified

    at Socket.<anonymous> (/home/myuser/cybre/node_modules/system-installer/index.js:107:69)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:601:20)
success Saved 1 new dependency.
info Direct dependencies
└─ node-7z-forall@1.0.0
info All dependencies
└─ node-7z-forall@1.0.0
```
The important part being:
```console
Running sudo apt-get,install,libc6-i386,-y
Error: sudo: no tty present and no askpass program specified
```

I editted my sudo file using:
```console
$ sudo visudo
```
and added my user to the end of the file to not ask for a password for `apt-get`.
```console
myuser ALL = NOPASSWD: /usr/bin/apt-get
```
Then reinstalled with yarn and now I have binaries!
```console
$ yarn add node-7z-forall --verbose
```

**Comment by techno-express** [comment]
Not sure what could be done to prevent the issue, 
I expect the Linux version to be initially run as root no good automated secure way to get around.

The package has been update to account for the invalid download link for Linux.
